# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dest_address',
            field=models.CharField(max_length=250, verbose_name='Adresse de destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_address',
            field=models.CharField(max_length=250, verbose_name='Adresse de départ'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
