# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20170516_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reservation_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='create_date',
        ),
    ]
